### ISSUE TITLE
Account Username Validation

### ISSUE THREAD

**Issue by Cweorth** [Cweorth/Surreal-Travel#41]
Generally, usernames should be of the form ```[a-z0-9]*```, that is, no special characters, no uppercase characters and definitely NOT white spaces.

If we allowed uppercase letters or whitespaces, we could allow the following problematic names:
 - users with names ```user```, ```_user```, ```user_``` and ```_user_``` (```_``` means a space),
 - users with names ```user```, ```User``` and ```USER```.

Please, fix this in ```AccountDAO```. **This is not a bug** (per se), so no need to hurry.
@kiclus , please make sure your tests will cover this.

**Comment by FiXerCz** [comment]
It is done.

Username has constraints for allowed characters and length [5;32].

I have also added password length constraint [5;32]. To achieve this I had to add a new dummy attribute (not persisted) ```String plainPassword```, that checks for length. This attribute is set to ```AccountDTO``` (and therefore also to ```Account```) only when persisting or merging. I had to also modify ```CustomerController```, so that it adds plain password to our default administrator. If you have any significamt changes in this controller in your working copy, you can disregard my changes and use your version and then just add changes that I made (one call of a setter method).

@kiclus When testing for not allowed characters or incorrect length, catch ```javax.validation.ConstraintValidationException```. That is thrown when error constraint violation occurs.
